### ISSUE TITLE
Rake Task to Remove Existing Seed Files

### ISSUE THREAD

**Issue by h0tl33t** [vigetlabs/sprig#34]
@ltk brought up the idea of adding a rake task to allow users to delete existing seed files (something like `db:seed:purge` or `sprig:files:clear`), which is now relevant since Sprig can create or append to seed files.  Users may want a clean slate before generating seed files from the database.

Some thoughts I had on this:
* Require the user to specify the environment (or folder name) to delete the seeds from, so that it's clear/explicit as to what will be deleted.
* Before deleting seed files, show the user a list of the files and provide a prompt asking whether or not they still want to continue with the deletion.

Anyone have other thoughts/additions?

**Comment by Fosome** [comment]
@h0tl33t Are you still interested in pursuing this?  We can put it on the roadmap.

**Comment by h0tl33t** [comment]
Not super clear if this is something many people have had a need for.  It's pretty easy to delete the files and/or directories themselves.  You have any thoughts?

**Comment by Fosome** [comment]
It's not something I've desired, but I haven't used `sprig-reap` yet.  Should be fairly easy to do.  Unless you're for it, I'll just close this out.

**Comment by h0tl33t** [comment]
Yeah, just close this for now.  We can always re-open if people ask for it.. but I doubt anyone will.
