### ISSUE TITLE
Add support for non-Rails environments

### ISSUE THREAD

**Issue by jgarber623** [vigetlabs/sprig#45]
(Based on a conversation with @ltk.)

To use Sprig with Sinatra, I had to [monkeypatch Sprig's configuration class](https://gist.github.com/jgarber623/74b34883c2a6a7188f3b) as it relies on `Rails.root`.

It'd be great if that method didn't rely on `Rails.root`.

**Comment by jgarber623** [comment]
Seems unlikely this one will ever happen, so… closing. 😁

**Comment by nhunzaker** [comment]
@jgarber623 Sorry about this. @ltk What do you think?

**Comment by nhunzaker** [comment]
In the mean time. @jgarber623 I'll do my best to keep up, but what do you think is the best way to accommodate Rails and Sinatra? Would exposing an option to specify the root be sufficient?

**Comment by Fosome** [comment]
Before committing to the idea - should this really happen?  Sprig has always been coupled to Rails:

`"Seed Rails application by convention, not configuration."`

Departing from this would at least be a large direction shift for Sprig.

**Comment by jgarber623** [comment]
☝️ I'm with Ribs.

**Comment by Fosome** [comment]
:+1: closing
