### ISSUE TITLE
find_existing_by for CSV and Custom Parsers

### ISSUE THREAD

**Issue by fny** [vigetlabs/sprig#50]
Is there any way to set options directly per model for CSVs and custom parsers?

**Comment by fny** [comment]
I didn't expect to be able to define both the options and records in a single file (although its great to know its possible).  Rather, it would be lovely to define the options in a Sprig consumable hash as follows:

```ruby
fanciness = {
  :class  => User,
  :source => open('https://spreadsheets.google.com/feeds/list/somerandomtoken/1/public/values?alt=json'),
  :parser => Sprig::Data::Parser::GoogleSpreadsheetJson
  :options => { find_existing_by: :email }
}
```

**Comment by ltk** [comment]
That's a good idea. It's not currently supported, but I don't think it would be too difficult to implement. I could start work on that early next week.

**Comment by ltk** [comment]
Turns out that this is already supported with a minor syntax tweak. Just omit the `:options` key:

```ruby
fanciness = {
  :class            => User,
  :source           => open('https://spreadsheets.google.com/feeds/list/somerandomtoken/1/public/values?alt=json'),
  :parser           => Sprig::Data::Parser::GoogleSpreadsheetJson
  :find_existing_by => :email
}
```

See https://github.com/vigetlabs/sprig/commit/8c96fb250c45b9a74d8db7c43558152db4ae39b6
