### ISSUE TITLE
getting repeated error

### ISSUE THREAD

**Issue by mikesmayer** [vigetlabs/sprig#52]
Hi,

Wondering if anyone can help me debug an error I'm getting when I try to seed via sprig.

rake aborted!
Psych::SyntaxError: (<unknown>): did not find expected key while parsing a block mapping at line 2 column 5
/Users/Mike/.rvm/gems/ruby-2.1.5@PartnerList3/gems/sprig-0.1.6/lib/sprig/parser/yml.rb:5:in `parse'
/Users/Mike/.rvm/gems/ruby-2.1.5@PartnerList3/gems/sprig-0.1.6/lib/sprig/source.rb:23:in `data'
/Users/Mike/.rvm/gems/ruby-2.1.5@PartnerList3/gems/sprig-0.1.6/lib/sprig/source.rb:10:in `records'
/Users/Mike/.rvm/gems/ruby-2.1.5@PartnerList3/gems/sprig-0.1.6/lib/sprig/seed/factory.rb:21:in `add_seeds_to_hopper'
/Users/Mike/.rvm/gems/ruby-2.1.5@PartnerList3/gems/sprig-0.1.6/lib/sprig/directive_list.rb:10:in `block in add_seeds_to_hopper'
/Users/Mike/.rvm/gems/ruby-2.1.5@PartnerList3/gems/sprig-0.1.6/lib/sprig/directive_list.rb:9:in `each'
/Users/Mike/.rvm/gems/ruby-2.1.5@PartnerList3/gems/sprig-0.1.6/lib/sprig/directive_list.rb:9:in `add_seeds_to_hopper'
/Users/Mike/.rvm/gems/ruby-2.1.5@PartnerList3/gems/sprig-0.1.6/lib/sprig/helpers.rb:9:in `sprig'
/Users/Mike/Code/PartnerList3/db/seeds/development.rb:5:in `<top (required)>'

I'm not sure what the first line, "did not find expected key while parsing a block mapping at line 2 column 5" is telling me.

Any thoughts?

**Comment by ltk** [comment]
That usually means there's a syntax error in the yaml file preventing it from being parsed. Could you throw the file contents into a gist and share the link?

**Comment by mikesmayer** [comment]
4 of my models (Consultants, Firms, Staffers and Vendors) have STI models (xxxxaccount, xxxxprospect, xxxxstub), here the data is grouped by each of the top level models with the type called out as an attribute.

I was getting the same failure when I tried to run the seeding process across all the individual seed files for the models (12 STI models and 3 plain jane models).

Thanks for taking a look.

development.rb
https://gist.github.com/mikesmayer/1ed33084416295a63db4

consultants.yaml
https://gist.github.com/mikesmayer/c5f7d00a537907c1b5b5

firms.yml
https://gist.github.com/mikesmayer/edd6f2581d0eb25770a6

peerpartnerships.yml
https://gist.github.com/mikesmayer/d781c99748cfcae8d58e

staffers.yml
https://gist.github.com/mikesmayer/82b5c0adb17aba4c7070

statuses.yml
https://gist.github.com/mikesmayer/067b96c026b7a90ee8bb

users.yml
https://gist.github.com/mikesmayer/6db40fd9c0674175bdad

vendors.yml
https://gist.github.com/mikesmayer/025d234577b1cd007170

**Comment by ltk** [comment]
Looks like you have some commas following lines in firms.yml that constitute invalid YAML syntax.

**Comment by mikesmayer** [comment]
Wow! This is fabulous. I've mostly gotten it working.

Is there anyway to force creation of a record?

I'm using a friendship/reverse-friendship model to create two way associations between objects. When sprig creates a seed record that is in a state of blocked, the system throws the expected message preventing the creation of the reverse-friendship that should also be marked blocked.

In my former seed file, I used an ! exclamation point to force the creation of the two friendships like so:

Peerpartnership.request(seed_consultantaccount, person8).block!

**Comment by ltk** [comment]
Interesting idea. There's not currently a way to force the creation, but that I could see that being a useful option. I'll experiment with this later this week. I'm gonna close this issue and open a new enhancement issue with that suggestion.
