### ISSUE TITLE
logger configuration

### ISSUE THREAD

**Issue by bitterloa** [vigetlabs/sprig#57]
hi, first off want to say that both sprig and sprig-reap are awesome! just what i needed. I have a question about configuring the logger: I notice in the newest code that you added the ability to have a configurable logger for sprig, but i'm unsure how to do this correctly? My issue is that when running tests I use sprig to populate certain tables, but I'm getting too much info logged out in my rspec tests. Can I turn off logging for the test environment only? I was thinking something like this:

```
Sprig.configure do |c|
  c.logging = :off if [RAILS_ENV]=="test"
end
```

Is it possible to turn off sprig logging in the test environment, or better yet adjust the logging level to only show up for errors? Thanks!

**Comment by ltk** [comment]
Something like this should work:

```ruby
Sprig.configure do |c|
  if [RAILS_ENV] == "test"
    c.logger = Logger.new("/dev/null")
  end
end
```

Let me know if that doesn't suit your needs.

Thanks for the feedback!

**Comment by bitterloa** [comment]
yes! it worked! For anyone else needing the final code that worked for me it's below. I needed to specify the rails environment using `Rails.env`. Put this file in `config/initializers/sprig.rb`

```
Sprig.configure do |c|
  # turn off logging in test environment
  if Rails.env == "test"
    c.logger = Logger.new("/dev/null")
  end
end
```

As a follow up, but honestly it's no big deal, is there a way to specify the log level to show only errors instead of completely turning them off? In any case, the above worked to turn them off so thanks for that.
