### ISSUE TITLE
Is it possible to pass in a variable with the command?

### ISSUE THREAD

**Issue by burtondav** [vigetlabs/sprig#58]
I'm using the gem 'acts_as_tenant' in a Rails 3 project.

I would like to seed new data every time a new Tenant is added - but only for the new Tenant.

Is there a way to pass a variable to Sprig?

Something like:

rake db:seed -tenant=5

**Comment by ltk** [comment]
I *believe* that env variables are accessible within your seed files (although I'm not totally sure about this). You could possibly do something like `TENANT=5 rake db:seed` with a seed file that had attributes like `tentant_id: "<%= ENV['TENANT']" %>`

If I were you I might use a custom datasource which would give you complete control over how the seeds records are built: http://vigetlabs.github.io/sprig/about.html#flexible-and-customizable

**Comment by mackermedia** [comment]
Or... you might consider using ActiveRecord::Callbacks to achieve what seems like you're describing as "default data".

Some links that you may find useful:
* http://guides.rubyonrails.org/active_record_callbacks.html
* http://stackoverflow.com/questions/328525/how-can-i-set-default-values-in-activerecord

**Comment by burtondav** [comment]
Thanks for the help!
