### ISSUE TITLE
unique records with Sprig

### ISSUE THREAD

**Issue by benams** [vigetlabs/sprig#67]
Hi, 
I have a json seed file:
{
  "records":
    {
      "spring_id": 1,
      "name": "N1"
    },
    {
      "spring_id": 2,
      "name": "N2"
    },
    {
      "spring_id": 3,
      "name": "N3"
    }
}

Every time I seed, the 3 networks are created and I get duplicate networks. There is any way to avoid it and mark those records as unique?

**Comment by efatsi** [comment]
See the [`find_existing_by`](https://github.com/vigetlabs/sprig#special-options) option in the README.

**Comment by benams** [comment]
Ok, it really works, but it throws an error... Why? 
Getting error every time I seed is not the expected seed behavior as far as I know.
