### ISSUE TITLE
what is the correct syntax for calling sprig_id when parsing json from a Google Spreadsheet?

### ISSUE THREAD

**Issue by mikesmayer** [vigetlabs/sprig#68]
I'm trying to load records into my application from a Google Spreadsheet and would like to use the intelligent insertion of Sprig, but can't seem to figure out the right way to name the column value and the sprig_id.

In YML file, I would do this:

records:
  - sprig_id: 1
    user_id: "<%= sprig_record(User, 2).id %>"
    employable_id: "<%= sprig_record(Firm, 82).id %>"

But the parser seems to remove "_" (underscore characters from column headers -- any work around?

Thanks!

**Comment by ltk** [comment]
Unfortunately Google strips those underscores. It's a quite unfortunate occurrence. It makes working reliably with their spreadsheet JSON pretty untenable.

You can check out the raw JSON response for my updated test-case spreadsheet here: https://spreadsheets.google.com/feeds/list/0AnHDMOkVdZKVdEhxTlc3VnJIbll1TlJUR0JFNngxQ3c/1/public/values?alt=json

The only way I can think of to make this work is for the Google spreadsheet parser to look for `sprigid`, and inject the underscore back in. Not lovely.

**Comment by mikesmayer** [comment]
Are you able to successfully seed the database with your spreadsheet? I've looked at your example spreadsheet, I think this is the graphical view? 

https://spreadsheets.google.com/pub?key=0AnHDMOkVdZKVdEhxTlc3VnJIbll1TlJUR0JFNngxQ3c

Your column A has a title of 'sprig_id', when I try that I get:

NoMethodError: undefined method `sprigid=' for #<Descriptor:0x007fa0664a9670>


Here's the output:

D, [2015-04-23T10:27:09.567240 #20895] DEBUG -- : Planting those seeds...
rake aborted!
NoMethodError: undefined method `sprigid=' for #<Descriptor:0x007fa0664a9670>
/Users/Mike/.rvm/gems/ruby-2.1.5@PartnerList3/gems/activemodel-4.2.0.rc3/lib/active_model/attribute_methods.rb:433:in `method_missing'
/Users/Mike/.rvm/gems/ruby-2.1.5@PartnerList3/gems/sprig-0.1.7/lib/sprig/seed/record.rb:35:in `block in populate_attributes'
/Users/Mike/.rvm/gems/ruby-2.1.5@PartnerList3/gems/sprig-0.1.7/lib/sprig/seed/attribute_collection.rb:6:in `each'
/Users/Mike/.rvm/gems/ruby-2.1.5@PartnerList3/gems/sprig-0.1.7/lib/sprig/seed/attribute_collection.rb:6:in `each'
/Users/Mike/.rvm/gems/ruby-2.1.5@PartnerList3/gems/sprig-0.1.7/lib/sprig/seed/record.rb:34:in `populate_attributes'
/Users/Mike/.rvm/gems/ruby-2.1.5@PartnerList3/gems/sprig-0.1.7/lib/sprig/seed/record.rb:21:in `save'
/Users/Mike/.rvm/gems/ruby-2.1.5@PartnerList3/gems/sprig-0.1.7/lib/sprig/seed/entry.rb:30:in `save_record'
/Users/Mike/.rvm/gems/ruby-2.1.5@PartnerList3/gems/sprig-0.1.7/lib/sprig/planter.rb:31:in `plant'
/Users/Mike/.rvm/gems/ruby-2.1.5@PartnerList3/gems/sprig-0.1.7/lib/sprig/planter.rb:9:in `block in sprig'
/Users/Mike/.rvm/gems/ruby-2.1.5@PartnerList3/gems/sprig-0.1.7/lib/sprig/planter.rb:8:in `each'
/Users/Mike/.rvm/gems/ruby-2.1.5@PartnerList3/gems/sprig-0.1.7/lib/sprig/planter.rb:8:in `sprig'
/Users/Mike/.rvm/gems/ruby-2.1.5@PartnerList3/gems/sprig-0.1.7/lib/sprig/helpers.rb:10:in `sprig'
/Users/Mike/Code/PartnerList3/db/seeds/development.rb:19:in `<top (required)>'
/Users/Mike/.rvm/gems/ruby-2.1.5@PartnerList3/gems/activesupport-4.2.0.rc3/lib/active_support/dependencies.rb:268:in `load'
/Users/Mike/.rvm/gems/ruby-2.1.5@PartnerList3/gems/activesupport-4.2.0.rc3/lib/active_support/dependencies.rb:268:in `block in load'
/Users/Mike/.rvm/gems/ruby-2.1.5@PartnerList3/gems/activesupport-4.2.0.rc3/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/Mike/.rvm/gems/ruby-2.1.5@PartnerList3/gems/activesupport-4.2.0.rc3/lib/active_support/dependencies.rb:268:in `load'
/Users/Mike/Code/PartnerList3/db/seeds.rb:2:in `<top (required)>'
/Users/Mike/.rvm/gems/ruby-2.1.5@PartnerList3/gems/activesupport-4.2.0.rc3/lib/active_support/dependencies.rb:268:in `load'
/Users/Mike/.rvm/gems/ruby-2.1.5@PartnerList3/gems/activesupport-4.2.0.rc3/lib/active_support/dependencies.rb:268:in `block in load'
/Users/Mike/.rvm/gems/ruby-2.1.5@PartnerList3/gems/activesupport-4.2.0.rc3/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/Mike/.rvm/gems/ruby-2.1.5@PartnerList3/gems/activesupport-4.2.0.rc3/lib/active_support/dependencies.rb:268:in `load'
/Users/Mike/.rvm/gems/ruby-2.1.5@PartnerList3/gems/railties-4.2.0.rc3/lib/rails/engine.rb:547:in `load_seed'
/Users/Mike/.rvm/gems/ruby-2.1.5@PartnerList3/gems/activerecord-4.2.0.rc3/lib/active_record/tasks/database_tasks.rb:252:in `load_seed'
/Users/Mike/.rvm/gems/ruby-2.1.5@PartnerList3/gems/activerecord-4.2.0.rc3/lib/active_record/railties/databases.rake:180:in `block (2 levels) in <top (required)>'
/Users/Mike/.rvm/gems/ruby-2.1.5@global/bin/ruby_executable_hooks:15:in `eval'
/Users/Mike/.rvm/gems/ruby-2.1.5@global/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:seed

**Comment by mikesmayer** [comment]
@ltk Are you able to successfully seed the database with your spreadsheet?

**Comment by ltk** [comment]
No, the google spreadsheet parser will need some hacky work to transform `sprigid` to `sprig_id`.
