### ISSUE TITLE
String sprig_ids

### ISSUE THREAD

**Issue by nhunzaker** [vigetlabs/sprig#77]
I'm not sure if this is currently supported, or already raised as an issue, but it would be nice to have string based sprig_ids so that it's easier to identify records. For example:

```
site_id: "<%= sprig_record(Site, 'bronxzoo').id %>"
```

Additionally, string ids prevent situations where you have auto-incrementing for sprig_ids and suddenly need to add a new record. For example:

```
# Queens Zoo zones
- sprig_id: 20
  name: 'Checkout'
  site_id: "<%= sprig_record(Site, 1).id %>"

- sprig_id: 21
  name: 'Field Trips'
  site_id: "<%= sprig_record(Site, 3).id %>"

# Prospect Park Zoo zones
- sprig_id: 22
  name: 'Checkout'
  site_id: "<%= sprig_record(Site, 4).id %>"

- sprig_id: 23
  name: 'Field Trips'
  site_id: "<%= sprig_record(Site, 4).id %>"
```

What if I add a new "zone" to Queens Zoo? Should I auto-increment all subsequent sprig_ids?

**Comment by efatsi** [comment]
`sprig_record` eventually calls `to_s` on the id field for saving and lookup, I believe this is already supported.

**Comment by nhunzaker** [comment]
Cool. Did some local testing and this is definitely the case. It simply be a matter of documentation. What if we made it clearer in the README, through examples, that string keys are also possible?

**Comment by ltk** [comment]
I just mixed up a bunch of the examples in the readme and doc site to include string sprig_ids. Hopefully that will suffice. Otherwise we can revisit again later.

**Comment by nhunzaker** [comment]
:+1:
