### ISSUE TITLE
Skipping before actions when using sprig

### ISSUE THREAD

**Issue by hickscorp** [vigetlabs/sprig#80]
When using sprig to seed existing objects, some of them might need to have their `before_save` / `before_create` skipped. It would be nice to have control over that.

For instance, if a snapshot of a database is being restored using sprig, some of the actual sprig seeds might contain relational objects that were in fact created in `before_create` callbacks, and those would then be wrongly duplicated in the seeding process.

What would be an acceptable workaround for doing something like that?

**Comment by ltk** [comment]
Hey @hickscorp, thanks for the issue.

Lifecycle hooks quickly turn into nightmare when you try to do too much with them. I've been burned by that before and now try to avoid them altogether.

What you're asking for may be possible with no change to Sprig via the [`skip_callback`](http://apidock.com/rails/ActiveSupport/Callbacks/ClassMethods/skip_callback) method baked into AR.

Have you tried something like this in your `seeds.rb`?

```ruby
include Sprig::Helpers

Post.skip_callback(:create, :before, :save)

sprig[Post]
```

**Comment by hickscorp** [comment]
@ltk Thank you for your detailed reply! My answers below.

## Lifecycle Hooks Answer

I usually don't use lifecycle hooks in my AR objects. There are exceptions to that rule. In particular I have a scenario right now, I'm going to try and make an analogy:

- Imagina a `Repository` model, having a `reference_count` column.
- When that `reference_count` reaches 1 from zero, the object has to register the webhooks to the github API.
- Reciprocally, when that `reference_count` reaches zero from 1, the object has to un-register web-hooks with the Github API.

When having an instance of such a model, the reference count could fluctuate arbitrarily. It could go from minus values to high values, go back down and up, etc.

As registering / unregistering the hooks with the Github API is long, we don't want it to do un-necessary calls! Therefore in such situation, we have several pieces of logic in `before_save` and `after_destroy`.

Is my example clear enough?

## Skipping Callbacks Answer

Using vanilla `skip_callback` indeed worked. Thanks for that, I was too focused on trying to find a solution with `sprig`. Sorry for the noise.

Thanks, and keep up the good work.

**Comment by ltk** [comment]
super. glad `skip_callback` worked for you. 

The pattern I find myself reaching for when I find myself with complex lifecycle hooks is update objects like the one below. It doesn't work in all cases, but it can sometimes be nice to wrap up complex processes into their own abstraction. (Makes things sooo much easier to test as well.)

```ruby
class ReferenceRemoval
  def initialize(params={})
    @reference_id = params.fetch(:reference_id)
    @repository   = params.fetch(:repository)
  end

  def perform
    Repository.transaction do
      repository.references.find(reference_id).destroy
      update_webhooks
    end
  end

  private

  attr_reader :reference_id, :repository

  def update_webhooks
    repository.remove_webhook if repository.reference_count < 1
  end
end
```
