### ISSUE TITLE
Psych::SyntaxError

### ISSUE THREAD

**Issue by dcalixto** [vigetlabs/sprig#84]
I followed the tutorial added 
include Sprig::Helpers
sprig [ Category, Subcategory]

on top of seeds.rb

and:

```
rake aborted!
Psych::SyntaxError: (<unknown>): did not find expected key while parsing a block mapping at line 12 column 5
/Users/dcalixto/lokks/db/seeds.rb:5:in `<top (required)>'
Tasks: TOP => db:seed
```

someone is having this issue?

**Comment by ltk** [comment]
Can you share the path to and contents of your seed files? (Should be `categories.yml` and `subcategories.yml`.)

**Comment by dcalixto** [comment]
shure @ltk  and thank's for your reply.

**lokks/db/seeds/production**

_categories.yml_
records:
  - sprig_id: 1
    name: "Clothes"
    name: "Footwear"
    name: "Accessories"


_subcategories.yml_

records:
  - sprig_id: 1
    category_id: "<%= sprig_record(Category, 1).id %>"
    name: "T-shirts"

  - sprig_id: 1
    category_id: "<%= sprig_record(Category, 2).id %>"
    name: "Shoes"

 - sprig_id: 1
    category_id: "<%= sprig_record(Category, 3).id %>"
    name: "Necklaces"

**Comment by ltk** [comment]
I see a few issues here:

First, the `sprig_id` field should be unique across records of the same type.
Second, You seem to be referencing records which do not exist (e.g. `sprig_record(Category, 3).id`). The `3` there should correspond to a `sprig_id` within `categories.yml`
Third, is the indentation correct for all the entries in `subcategories.yml`, or did it just get messed up when you pasted it as a comment here?

Finally, be sure that you are running the seed process in the `production` env if that's the env for which your seeds are defined.

**Comment by dcalixto** [comment]
So this should be?

Categories:
sprig_id: 1 name: "Clothes" 
sprig_id: 2 name: "Footwear" 
sprig_id: 3 name: "Accessories" 

Subcategories:
sprig_id: 1 category_id: "<%= sprig_record(Category, 1).id %>" name: "Clothes"
sprig_id: 2 category_id: "<%= sprig_record(Category, 2).id %>" name: "Footwear"
sprig_id: 3 category_id: "<%= sprig_record(Category, 3).id %>" name: "Acessoies"

but if i would like to put more than one subcategory per category or category per subcaregory and a third category? 

for exemple:
() = have
category >>>>  item 1 item 2 item 3 
subcategory >>>> item 2(subitem 1 subitem 2 subitem 3)
thirdcategory >>>> subitem 3(thirditem 1 thirditem 2)

as you said the sprig_id have to be the same.

and yes the comment messed up the indentation.

**Comment by Fosome** [comment]
Able to close?
