### ISSUE TITLE
Sprig 0.3.0 is not published

### ISSUE THREAD

**Issue by robert-damoc** [vigetlabs/sprig#99]
It seems that the last visible version of this gem is `0.2.0` - [rubygems](https://rubygems.org/gems/sprig/versions/0.2.0).

Could you release the last version on rubygems?

**Comment by rubendinho** [comment]
Any update on this?

**Comment by efatsi** [comment]
This is a little odd. I see that the 0.3.0 release is indeed published, but not sitting as the default version. Not sure what to make of that, but I'm able to pull 0.3.0 from rubygems successfully.

<img width="352" alt="screen shot 2019-01-22 at 10 03 25 am" src="https://user-images.githubusercontent.com/1410181/51552026-fb98cc00-1e2c-11e9-80a0-b6f37df1c20a.png">

**Comment by efatsi** [comment]
Oh, your link specifically called out 0.2.0 as the version. https://rubygems.org/gems/sprig shows 0.3.0.

**Comment by rubendinho** [comment]
I had forked it before 0.3.0 was published and yes I see now that 0.3.0 is published.  Thanks!
